id: PFB6D94AD
initial_creation_type: input
source_metadata:
  Title: Abhidharmasamuccayabhāṣyam
  Editor: Tatia, Nathmal
  Publisher: K.P.Jayaswal Research Institute
  Place of Publication: Patna,India
  Year: '2005'
  Lakṣaṇasamuccayo nāma prathamaḥ samuccayaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Satyaviniścayo nāma dvitīyaḥ samuccayaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Dharmaviniścayo nāma tṛtīyaḥ samuccayaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Prāptiviniścayo nāma caturthaḥ samuccayaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Sāṃkathyaviniścayo nāma pañcamaḥ samuccayaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:17:52.484641'
last_modified_at: '2022-03-08T16:17:52.484649'
